config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "about" => "top#about"
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.order("number")
  end

  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Morning Glory"
    title = @page_title + " - " + title if @page_title
    title
  end

  def menu_link_to(text, path, options = {})
    content_tag :li do
      link_to_unless_current(text, path, options) do
        content_tag(:span, text)
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asagao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <header>
        <%= render "shared/header" %>
      </header>
      <main>
        <%= yield %>
      </main>
      <aside id="sidebar">
        <%= render "shared/sidebar" %>
      </aside>
      <footer>
        <%= render "shared/footer" %>
      </footer>
    </div>
  </body>
</html>

app/views/members/index.html.erb
<% @page_title = "会員名簿" %>
<h1><%= @page_title %></h1>



<% if @members.present? %>
  <table class="list">
    <thead>
      <tr>
        <th>背番号</th>
        <th>ユーザー名</th>
        <th>氏名</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td style="text-align: right"><%= member.number %></td>
          <td><%= link_to member.name, member %></td>
          <td><%= member.full_name %></td>
          <td>
            <%= link_to "編集", [:edit, member] %> |
            <%= link_to "削除", member, method: :delete,
              data: { confirm: "本当に削除しますか?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>会員情報がありません。</p>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", about_path %>
Copyright (C) <%= link_to "Oiax Inc.", "http://www.oiax.co.jp/" %>
2007-2018

app/views/shared/_header.html.erb
<%= image_tag "logo.gif", size: "272*48", alt: "Morning Glory" %>
<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <%= menu_link_to "ニュース", "#" %>
    <%= menu_link_to "ブログ", "#" %>
    <%= menu_link_to "会員名簿", members_path %>
    <%= menu_link_to "管理ページ", "#" %>
  </ul>
</nav>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<form id="login-form">
  <div>
    <label>ユーザー名：</label>
    <input type="text">
  </div>
  <div>
    <label>パスワード：</label>
    <input type="password">
  </div>
  <div>
    <input type="submit" value="ログイン">
  </div>
</form>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" %>

<h2>最新ニュース</h2>
<ul>
  <% 5.times do |i| %>
    <li><%= link_to "ニュースの見出し", "#" %></li>
  <% end %>
</ul>

<h2>会員のブログ</h2>
<ul>
  <% 5.times do |i| %>
    <li><%= link_to "ブログの見出し", "#" %></li>
  <% end %>
</ul>

app/views/top/about.html.erb
<% @page_title = "このサイトについて" %>

<h1><%= @page_title %></h1>

app/views/top/index.html.erb
<% 5.times do |x| %>
  <h2>見出し</h2>
  <p>
    ここに本文が入ります。ここに本文が入ります。ここに本文が入ります。ここに本文が入ります。
    <%= link_to "もっと読む", "#" %>
  </p>
<% end %>